[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
tokio = { workspace = true }
feeder = { workspace = true }
event_engine = { workspace = true }
market_agent = { workspace = true }
core_affinity = { workspace = true }
