[package]
name = "event_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
ringbuf = { workspace = true }  # 让 sublib 使用 workspace 共享的 ringbuf
serde = { workspace = true }
chrono = { workspace = true }